In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
size = 10


In [50]:
def west_facing_triangle(size: int) -> np.ndarray:
    grid = np.zeros((size, size))
    left_tri = np.ones_like(grid[:grid.shape[0] // 2, :])
    bottom_half = np.triu(left_tri, k=size // 4 + 1)
    top_half = np.flip(bottom_half, axis=0)
    return np.concatenate((top_half, bottom_half), axis=0)

def north_facing_triangle(size: int) -> np.ndarray:
    west = west_facing_triangle(size)
    return west.T

def east_facing_triangle(size: int) -> np.ndarray:
    return np.flip(west_facing_triangle(size), axis=1)

def south_facing_triangle(size: int) -> np.ndarray:
    return np.flip(north_facing_triangle(size), axis=0)

In [51]:
south_facing_triangle(size)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
top_half

array([[0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
width = 2
grid = np.zeros((size, size))
left_tri = np.ones_like(grid[:grid.shape[0] // 2, :])
bottom_half = np.triu(left_tri, k=size // 4 + 1)
top_half = np.flip(bottom_half, axis=0)

bs = np.triu(left_tri, k=size // 4 + 1 + width)
ts = np.flip(bs, axis=0)
smaller = np.concatenate((ts, bs), axis=0)
larger = np.concatenate((top_half, bottom_half), axis=0)

In [42]:
grid = np.zeros((size, size))
indices = np.arange(size)
grid[indices, indices] = 1
rev_diag = np.flip(grid, axis=0)
cross = np.maximum(grid, rev_diag)
cross

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
up_tri = np.triu(grid)
east = np.flip(up_tri, axis=0) * up_tri
south = east.T
west = np.flip(east, axis=1)
north = np.flip(south, axis=0)

In [39]:
north

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])